name: Prod Upgrade Release
on:
  schedule:
    # Every Sunday at 9PM UTC
    - cron: '0 21 * * 0'
permissions:
  contents: write
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
