name: Prod Upgrade Release
on:
  schedule:
    - cron: '20 23 * * 0'
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
